In [4]:
import pandas as pd

In [6]:
pd.__version__

'1.0.5'

In [7]:
list_val=[1,2,3,4,5,'data_value']

In [8]:
print(list_val)

[1, 2, 3, 4, 5, 'data_value']


In [9]:
series1=pd.Series(list_val)

In [10]:
print(series1)

0             1
1             2
2             3
3             4
4             5
5    data_value
dtype: object


In [11]:
type(series1)

pandas.core.series.Series

In [12]:
series2=pd.Series([1,2,3,4,4,5])
print(series2)

0    1
1    2
2    3
3    4
4    4
5    5
dtype: int64


In [15]:
series3=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(series3)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [16]:
series3=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'],dtype='float')
print(series3)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
dtype: float64


In [17]:
series3=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'],dtype='float',name='data value')
print(series3)

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
Name: data value, dtype: float64


In [20]:
series3[0:3]

a    1.0
b    2.0
c    3.0
Name: data value, dtype: float64

In [21]:
dict1 = {'ID': [11,22,33,44]}   # Creating dict
dict1

{'ID': [11, 22, 33, 44]}

In [22]:
dict2 = {'ID': [11,22,33,44], 'SN': [1,2,3,4]}
dict2

{'ID': [11, 22, 33, 44], 'SN': [1, 2, 3, 4]}

In [27]:
df4 = pd.DataFrame(dict2)

In [24]:
df4

ID
0  11
1  22
2  33
3  44

In [28]:
ls_dict = [{'a':1, 'b':2}, {'a':3, 'b':4, 'c':5}]   
df6 = pd.DataFrame(ls_dict)
df6

a  b    c
0  1  2  NaN
1  3  4  5.0

In [29]:
import numpy as np # import numpy package
one_d_array = np.array([1,2,3,4]) # create 1D array
print(one_d_array) # printing 1d array

[1 2 3 4]


In [30]:
import numpy as np # impoer numpy package
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 1D array
print(two_d_array) #printing 2D array

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
arr = np.arange(1,13,3)
print(arr)


[ 1  4  7 10]


In [34]:
np.linspace(1,5,4)


array([1.        , 2.33333333, 3.66666667, 5.        ])

In [37]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
 

In [38]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [41]:
ar=np.arange(1,13).reshape(6,2)
print(ar)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [42]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [43]:
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [44]:
df1 = pd.DataFrame({'A': [1,2,3],
                   'B': [10,20,30]})
 
 
df2 = pd.DataFrame({'A': [4,5,6],
                   'B': [40,50,60]})

In [46]:
display(df1,df2)

A   B
0  1  10
1  2  20
2  3  30

A   B
0  4  40
1  5  50
2  6  60

In [49]:
df1.append(df2, ignore_index = True)

A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
5  6  60