In [1]:
import numpy as np

In [2]:
list1=np.array([1,2,4,5,6])

In [3]:
list1

array([1, 2, 4, 5, 6])

In [4]:
result=1

i=1

while i<=5:
    result=result*i
    i=i+1
print(result)

120


In [5]:
today = "Saturday"
print("Today is", today)

Today is Saturday


In [6]:
def say():
    print("hello how are you")
    print("say hello")

In [7]:
say()

hello how are you
say hello


In [8]:
def say_hello():
    print('Hello there!')
    print('How are you?')

In [9]:
say_hello()

Hello there!
How are you?


In [10]:
def filter_even(number_list):
    result_list = []
    for number in number_list:
        if number % 2 == 0:
            result_list.append(number)
    return result_list

In [11]:
def funtion_even(number_list):
    result_list=[]
    for num in number_list:
        if num%2==0:
            number_list.append(num)
            return result_list

In [12]:
even_list

NameError: name 'even_list' is not defined

In [ ]:
def filter_even(number_list):
    result_list = []
    for number in number_list:
        if number % 2 == 0:
            result_list.append(number)
            return result_list

In [ ]:
even_list=funtion_even([20,30,40,13])

In [13]:
even_list

NameError: name 'even_list' is not defined

In [14]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [15]:
list("Hello")

['H', 'e', 'l', 'l', 'o']

In [16]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [17]:
a=np.arange(10).reshape((2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
a=np.empty((1,8))
a

array([[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 6.03e-321,
        0.00e+000, 0.00e+000]])

In [20]:
np.sort(a)

array([[0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000,
        0.00e+000, 6.03e-321]])

In [21]:
np.ones(10).dtype

dtype('float64')

In [22]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
ar=np.array([[1,2,3,4],[5,6,7,8]])

In [24]:
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
ar[1,3]

8

In [26]:
ar[0:1]

array([[1, 2, 3, 4]])

In [27]:
ar[0,2]

3

In [28]:
num=0
if num>0:
    print("number is positive")
elif num==0:
    print("no is zero")
else:
    print("no is negative")

no is zero


In [29]:
a=int(input("Enter the first no"))
b=int(input("Enter the second no"))
c=int(input("Enter the third no"))
if (a>b) and (a>c):
    largest=a
elif (b>a)and (b>c):
    largest=b
else:
    largest=c
print("largest no is ",largest)

Enter the first no12
Enter the second no12
Enter the third no34
largest no is  34


###### Prime no

In [30]:
num=int(input("Enter a number"))
i=2
flag=False
while num>0:
    if (num%i)==0:
        flag=True
        break
if flag==True:
    print("no is not prime")
else:
    print("no is prime")
            
        

Enter a number14
no is not prime


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(1,-1)

print(newarr)

[[1 2 3 4 5 6]]


In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() ### only copy the into the new array
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [34]:
arr1=np.array([[2,3,4],[6,7,8]])

In [35]:
arr1

array([[2, 3, 4],
       [6, 7, 8]])

In [36]:
arr1.sum(axis=0)

array([ 8, 10, 12])

In [37]:
arr1.sum(axis=1)

array([ 9, 21])

In [39]:
#dir(np)

In [42]:
## 4. How to combine many series to form a dataframe?
import pandas as pd

In [43]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [49]:
ser_df = pd.DataFrame(ser1, ser2).reset_index()
ser_df.head()
ser_df1=pd.DataFrame(ser1,ser2).reset_index()

In [53]:
ser_df1

index  0
0       0  a
1       1  b
2       2  c
3       3  e
4       4  d
5       5  f
6       6  g
7       7  h
8       8  i
9       9  j
10     10  k
11     11  l
12     12  m
13     13  n
14     14  o
15     15  p
16     16  q
17     17  r
18     18  s
19     19  t
20     20  u
21     21  v
22     22  w
23     23  x
24     24  y
25     25  z

In [51]:
ser_df = pd.concat([ser1, ser2], axis = 1)
ser_df.head()

0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4

In [58]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

In [60]:
# using series rename method
ser.rename("alphabets")
# using series attribute
ser.name = "other_name"
ser

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: other_name, dtype: object

In [61]:
##6. How to get the items of series A not present in series B?

In [62]:
np.random.RandomState(100)

RandomState(MT19937) at 0x2303EE37440

In [63]:
ser = pd.Series(np.random.randint(1, 5, 10))
ser

0    1
1    4
2    1
3    2
4    2
5    2
6    4
7    4
8    1
9    1
dtype: int32

In [68]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

In [69]:
ser1=pd.Series(range(5))
ser2=pd.Series(list('abcd'))

In [73]:
# vertical
ser1.append(ser2)
# or using pandas concat and axis = 0
pd.concat([ser1, ser2], axis = 0)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
dtype: object

In [74]:
# horizontal
pd.concat([ser1, ser2], axis = 1)

0    1
0  0    a
1  1    b
2  2    c
3  3    d
4  4  NaN

In [75]:
# input
ser = pd.Series(['just', 'a', 'random', 'list'])

In [76]:
# using list comprehension
[len(i) for i in ser]

[4, 1, 6, 4]

In [77]:
# using series map
ser.map(len)

0    4
1    1
2    6
3    4
dtype: int64

In [79]:
ser.apply(len)

0    4
1    1
2    6
3    4
dtype: int64

In [80]:
#21. How to convert a series of date-strings to a timeseries?

In [81]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

In [82]:
type(ser)

pandas.core.series.Series

In [86]:
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [90]:
a=int(input())
b = int(input())
print('{0} \n{1} \n{2}'.format((a + b), (a - b), (a * b)))

3
4
7 
-1 
12


In [96]:
arr = np.array([[1, 2, 3], [4, 5, 6],[25,8,9]])

In [97]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [25,  8,  9]])

In [98]:
arr[::-1,]

array([[25,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [99]:
arr[::-1]

array([[25,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [100]:
arr[::,0]

array([ 1,  4, 25])