# Numpy Array

In [1]:
import numpy as np
type(np.array(["vbhvh", 2, 3]))

numpy.ndarray

In [2]:
#Upcasting:

In [3]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

In [4]:
l=[]

In [5]:
n_list = ["Happy", [2, 0, 1, 5]]
print(n_list[0][2])
print(n_list[1][3])

p
5


In [6]:
my_list = ['p','r','o','g','r','a','m','i','z']

# elements 3rd to 5th
print(my_list[2:5])

# elements beginning to 4th
print(my_list[:-5])

# elements 6th to end
print(my_list[5:])

# elements beginning to end
print(my_list[:])

['o', 'g', 'r']
['p', 'r', 'o', 'g']
['a', 'm', 'i', 'z']
['p', 'r', 'o', 'g', 'r', 'a', 'm', 'i', 'z']


In [7]:
user_input = str(input("Enter a Phrase: "))
text = user_input.split()
print(text)
a = " "
for i in text:
    a = a+str(i[0]).lower()
print(a)

Enter a Phrase: manish
['manish']
 m


In [8]:
num1 = 1.5
num2 = 6.3

# Add two numbers
sum = num1 + num2

# Display the sum
print('The sum of {0} and {1} is {2}'.format(num1, num2, sum))

The sum of 1.5 and 6.3 is 7.8


In [9]:
l=[1,2,3,4]

type(np.array(l))

numpy.ndarray

In [10]:
#two dimensions

In [11]:
 np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [12]:
#Minimum dimensions 2:

In [13]:
np.array([1, 2, 3], ndmin=7)

array([[[[[[[1, 2, 3]]]]]]])

In [14]:
#dtype

In [15]:
 np.array([1, 2, 3], dtype=complex)
import numpy as np 
x = np.empty([3,2], dtype = float) 
print(x)

[[1. 0.]
 [2. 0.]
 [3. 0.]]


In [16]:
#Data-type consisting of more than one element:

In [17]:
x = np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [18]:
x[1][0]

3

In [19]:

#Creating an array from sub-classes:

In [20]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [21]:
np.mat('1 2; 3 4')

matrix([[1, 2],
        [3, 4]])

In [22]:
np.mat('1 2 3;3 5 6')

matrix([[1, 2, 3],
        [3, 5, 6]])

# numpy.asarray

In [23]:
#Convert the input to an array.

In [24]:
#Convert a list into an array:

In [25]:
 a = [1, 2]
type(a)

list

In [26]:
my_set = {1, 2, 3, 4, 3, 2}
print(my_set)
my_set1 = set([1, 2, 3, 2])
print(my_set1)
type(my_set1)
my_set2 = set([1,3,4])
print(my_set2)
for letter in set("apple"):
    print(letter)

{1, 2, 3, 4}
{1, 2, 3}
{1, 3, 4}
e
p
a
l


In [27]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -4])

Last element from 2nd dim:  7


In [28]:
a=np.array([1,2,3,4,5,6,7])
a
type(a)
b=a
b
c=np.array(a,copy=True)
c[1]=200
c
id(a)
c[0]=2345
c

array([2345,  200,    3,    4,    5,    6,    7])

In [29]:
a[0]

1

In [7]:
# Frozensets
# initialize A and B
A = frozenset([1, 2, 3, 4])
B = frozenset([3, 4, 5, 6])

In [8]:
type(np.asarray(a))

NameError: name 'a' is not defined

In [9]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)
x = [1,2,3] 
a = np.asarray(x) 
type(a)

numpy.ndarray

In [33]:
np.asarray((1,2))

array([1, 2])

In [34]:
#If dtype is set, array is copied only if dtype does not match:

In [35]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [36]:
np.asarray([1,2]) is a

False

In [37]:
np.asarray([1,2])

array([1, 2])

In [38]:
np.asarray(a, dtype=np.float64) is a

False

In [39]:
# ndarray subclasses are not passed through

In [40]:
issubclass(np.matrix, np.ndarray)

True

In [41]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [42]:
np.asarray(a) is a

False

In [43]:
np.asanyarray(a) is a

True

In [44]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

In [45]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [46]:
a = np.matrix([1, 2])
a


matrix([[1, 2]])

In [47]:
np.asanyarray([1,2]) is a

False

In [48]:
np.array(a, copy=True)  

array([[1, 2]])

In [49]:
#Create an array x, with a reference y and a copy z:

In [50]:
x = np.array([1, 2, 3])
x


array([1, 2, 3])

In [51]:
y = x

In [52]:
z = np.copy(x)

In [53]:
y[0] = 100
x

array([100,   2,   3])

In [54]:
x

array([100,   2,   3])

In [55]:
id(x[0])

2674351053264

In [56]:
id(y[0])

2674351053616

In [57]:
id(x) 

2674351063248

In [58]:
id(y)

2674351063248

In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


# numpy.fromfunction

In [61]:
#Construct an array by executing a function over each coordinate.

In [62]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [63]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [64]:
#Create a new 1-dimensional array from an iterable object.

In [65]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x0000026EABBEE510>

In [66]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [67]:
#A new 1-D array initialized from text data in a string

In [68]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [69]:
np.fromstring('1, 2', dtype=float, sep=',')

array([1., 2.])

In [70]:
# How to create create a record array from a (flat) list of arrays

In [71]:
x1=np.array([1,2,3,4])

In [72]:
x2=np.array(['a','dd','xyz','12'])

In [73]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [74]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [75]:
print(r[1]["a"])

2


In [76]:
x1[1]

2

# data types

In [77]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [78]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [79]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [80]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

In [81]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [82]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [83]:
list(range(50,-1,5))

[]

In [84]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [85]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [86]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


In [87]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [88]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [89]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [90]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [91]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [92]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [93]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [94]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [95]:
np.arange(3)

array([0, 1, 2])

In [96]:
np.arange(3.0)

array([0., 1., 2.])

In [97]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [98]:
np.arange(3,7,2)

array([3, 5])

In [99]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [100]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [101]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [102]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [103]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [104]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [105]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [106]:
#Extract a diagonal or construct a diagonal array.

In [107]:
np.arange(16).reshape((2,8,2))

ValueError: cannot reshape array of size 16 into shape (2,8,2)

In [108]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [109]:
x = np.arange(16).reshape((-1,4))

In [110]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
np.diag(x)

array([ 0,  5, 10, 15])

In [112]:
np.diag(x, k=2
       )

array([2, 7])

In [113]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [114]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [115]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [116]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [117]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [118]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [119]:
np.tri(3, 5, 1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [120]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [121]:
#return a Lower triangle of an array.

In [122]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [123]:
#return Upper triangle of an array.

In [124]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

In [125]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.12424913 0.55695521 0.97377832]
 [0.00166109 0.99065445 0.59556871]]


In [126]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.59405797  0.59433553 -1.45268708]
 [-0.95063342  0.1586407  -0.95666319]
 [ 0.41375374  0.86752104  0.2380329 ]
 [-0.66614382  0.22203785 -0.27642219]]


In [127]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")


Random integer vector: 4

Random integer matrix


In [128]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[28 25 91  6]
 [25 37 58 93]
 [ 5 39 27 40]
 [97 65 79 43]]

20 samples drawn from a dice throw: [2 6 5 5 5 5 1 4 2 2 1 2 2 6 3 3 6 2 1 1]


In [129]:
import numpy as np

a=np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
a.shape
a[0][1]
a.reshape(2,3)
a.reshape(3,2)
a.ravel()
a
a.min()
a.max()
a.sum(axis=1)

array([ 3,  7, 11])

# Reshaping

In [131]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[70, 90, 52, 46, 12],
       [46, 17, 78, 35,  2],
       [90, 95, 22, 86, 34],
       [17, 70, 48, 54, 67],
       [14, 63, 68, 60, 51],
       [99, 32, 86, 82, 38]])

In [132]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [133]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [70 90 52 46 12 46 17 78 35  2 90 95 22 86 34 17 70 48 54 67 14 63 68 60
 51 99 32 86 82 38] 
 --------------------

b looks like
 -------------------- 
 [[[70 90 52 46 12]
  [46 17 78 35  2]
  [90 95 22 86 34]]

 [[17 70 48 54 67]
  [14 63 68 60 51]
  [99 32 86 82 38]]] 
 --------------------

c looks like
 -------------------- 
 [[70 90 52 46 12]
 [46 17 78 35  2]
 [90 95 22 86 34]
 [17 70 48 54 67]
 [14 63 68 60 51]
 [99 32 86 82 38]] 
 --------------------


In [134]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [135]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [60 57 32 38 19 84 42 17 30 23]

Here is the sorted vector
 -------------------------------------------------- 
 [17 19 23 30 32 38 42 57 60 84]


In [136]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 4 31 59 80 92]
 [59 77 84 91 94]
 [ 6  7 37 67 69]
 [ 6 19 42 45 76]
 [18 27 29 33 83]]


array([[ 4, 80, 59, 31, 92],
       [91, 77, 84, 94, 59],
       [ 6, 37,  7, 67, 69],
       [45, 76, 42, 19,  6],
       [18, 27, 29, 33, 83]])

In [137]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 94
Max of b: 99


array([[[70, 90, 52, 46, 12],
        [46, 17, 78, 35,  2],
        [90, 95, 22, 86, 34]],

       [[17, 70, 48, 54, 67],
        [14, 63, 68, 60, 51],
        [99, 32, 86, 82, 38]]])

In [138]:
M

array([[ 4, 80, 59, 31, 92],
       [91, 77, 84, 94, 59],
       [ 6, 37,  7, 67, 69],
       [45, 76, 42, 19,  6],
       [18, 27, 29, 33, 83]])

In [139]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a location: [4 3 4 1 4]
Max of b location: 25
Max of c location: 25


# Indexing and slicing

In [140]:
arr = np.arange(0,11)
print("Array:",arr)
arr[0]

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


0

In [141]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [142]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [143]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [145]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [146]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [147]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [148]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[46 26 68 18 49]
 [91 32 40 85 64]
 [61 36 73 75 41]]


array([[26, 18],
       [32, 85],
       [36, 75]])

In [149]:
mat[0:3,[1,3]]
mat

array([[46, 26, 68, 18, 49],
       [91, 32, 40, 85, 64],
       [61, 36, 73, 75, 41]])

In [150]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 32


array([[46, 26, 68, 18, 49],
       [91, 32, 40, 85, 64],
       [61, 36, 73, 75, 41]])

In [151]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 40

Row or column extract
----------------------


In [152]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])


Entire row at index 2: [61 36 73 75 41]
Entire column at index 3: [18 85 75]


In [153]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[85 64]
 [75 41]]


In [154]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[26 18]
 [32 85]]


# Subseting

In [155]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[25 60 28 96 54]
 [25 89 49 11 82]
 [26 89 68 30 74]]


array([[False,  True, False,  True,  True],
       [False,  True, False, False,  True],
       [False,  True,  True, False,  True]])

In [156]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [60 96 54 89 82 89 68 74]


# Slicing

In [157]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [158]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [159]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [160]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [161]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [162]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [163]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [164]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [165]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[2 6 2]
 [2 4 5]
 [9 5 6]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[4 9 9]
 [2 1 4]
 [9 5 4]]


In [166]:
mat1*mat2

array([[ 8, 54, 18],
       [ 4,  4, 20],
       [81, 25, 24]])

In [167]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 38  34  50]
 [ 61  47  54]
 [100 116 125]]


In [168]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


<ipython-input-168-ea15cab37cb9>:1: RuntimeWarning: divide by zero encountered in true_divide
  print("\nDivision\n------------------\n", mat1/0)


In [ ]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


In [ ]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))

# Broadcasting

In [ ]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [10]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [ ]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

In [ ]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

In [ ]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

In [113]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

NameError: name 'start' is not defined

In [ ]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

# Array Math

In [112]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


NameError: name 'ri' is not defined

In [ ]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


In [ ]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


In [ ]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)

In [ ]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2

In [ ]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)


In [ ]:
A = np.linspace(0,12*np.pi,1001)


In [ ]:
A